#include <unistd.h>
#include <signal.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/*This function needs two pipes. One to make the parent-child way and the other to make 
the child-parent way. The fork is then made, creating two processes. The parent process
will enter a while loop, while the credit is superior to 0. In this while loop, the parent 
will send the notification to the child, writing 1 in the pipe, because the credit is ">0".
The child reads this notification from the pipe and since it is 1, it means that the child 
can make a bet, so it generates a random number between 1 and 5 and sends it to the parent
through the pipe. Meanwhile, the parent also generated a random value between 1 and 5 and
after reading the number sent by the child from the pipe, it compares them. If they are the 
same, the credit increases by 10. If they are not, the credit decreases by 5. Then the parent
process sends the new updated credit to the child through the pipe and the child prints it.
This cycle repeats until the credit reaches 0, meaning that the child can't make more  bets. 
When it does, the while loop in the parent exits and the parent sends the notification with 0 
to the child. The child reads it and finishes its execution. Finally, the parent waits for 
the child to make sure it stopped executing.*/
int main(){
    int fd_wprc[2];
    int fd_rpwc[2];

    if (pipe(fd_wprc) == -1) {
        perror("Pipe1 failed!\n");
        return 1;
    }

    if (pipe(fd_rpwc) == -1) {
        perror("Pipe2 failed!\n");
        return 1;
    }

    pid_t pid = fork();

    if (pid == -1){
        printf ("Fork failed!\n");
        exit(EXIT_FAILURE);
    }

    if (pid > 0) {
        //parent 

        close(fd_wprc[0]);  //Close fd_wprc read
        close(fd_rpwc[1]);  //Close fd_rpwc write
        
        int credit = 20;
        int notification;

        while (credit > 0) {
            notification = 1;
            //Send notification
            if (write(fd_wprc[1], &notification, sizeof(int)) == -1){
                printf("Write failed!\n");
                exit(EXIT_FAILURE);
            }

            //Generate random number
            srand(time(NULL));
            int num = (rand() % 5) + 1;

            //Read the bet from the child
            int bet;
            if (read(fd_rpwc[0], &bet, sizeof(int)) == -1){
                printf("Read failed!\n");
                exit(EXIT_FAILURE);
            }

            //Compare the bet with the number generated by the parent
            if (bet == num){
                credit += 10;
            } else {
                credit -= 5;
            }

            //Send the updated credit
            if (write(fd_wprc[1], &credit, sizeof(int)) == -1){
                printf("Write failed!\n");
                exit(EXIT_FAILURE);
            }
        }

        //Send notification meaning that the child can't make more bets
        notification = 0;
        if (write(fd_wprc[1], &notification, sizeof(int)) == -1){
            printf("Write failed!\n");
            exit(EXIT_FAILURE);
        }

        wait(NULL);     //To make sure that the child process is finished

        close(fd_wprc[1]);  //Close fd_wprc write
        close(fd_rpwc[0]);  //Close fd_rpwc read

    } else {
        //child

        close (fd_wprc[1]);     //Close fd_wprc write
        close (fd_rpwc[0]);     //Close fd_rpwc read
        int notification;
        int credit;
        
        do {
            //Read the notification sent by the parent 
            if (read(fd_wprc[0], &notification, sizeof(int)) == -1){
                printf("Read failed!\n");
                exit(EXIT_FAILURE);
            }

            //Check which notification was sent 
            if (notification == 0){
                close(fd_wprc[0]);  //Close fd_wprc read
                close(fd_rpwc[1]);  //Close fd_rpwc write
                exit(EXIT_SUCCESS);

            } else {
                //Generate random number
                srand(time(NULL)+ 1);
                int bet = (rand() % 5) + 1;

                //Send the bet to the parent 
                if (write(fd_rpwc[1], &bet, sizeof(int)) == -1){
                    printf("Write failed!\n");
                    exit(EXIT_FAILURE);
                }

                //Read the updated credit
                if (read(fd_wprc[0], &credit, sizeof(int)) == -1){
                    printf("Read failed!\n");
                    exit(EXIT_FAILURE);
                }

                printf("New credit is %d\n", credit);
            }
        }while (notification == 1);        
    }
    return 0;
}