#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <time.h>
#define CHILDS_SIZE 5
#define SIZE 6
int main(){
	
	time_t t;															/* needed to initialize random number generator (RNG) */
	srand ((unsigned) time (&t));										/* intializes RNG (srand():stdlib.h; time(): time.h) */
    
    int fd[SIZE][2];

	for (int i = 0; i < SIZE; i++) {									// Creates 5 pipes 
		if (pipe(fd[i]) < 0) {
			perror("Pipe failed");
			exit(1);
		}
	}

	pid_t pid_array[CHILDS_SIZE];										//creation of an array of pid_t to create all child's
	int status_array[CHILDS_SIZE];

		
		int num = rand() % 50;
        printf("P: Process %d generated random number %d\n", getpid(), num);
	    write(fd[0][1], &num, sizeof(int));								//write the number generated by Parent process
	
	    
	for(int i = 0; i < CHILDS_SIZE;i++){								//fori cycle to create all childs
		
		int num = rand() % 50;
		
		pid_array[i] = fork();											//create cycle at position i of the pid_array

		if(pid_array[i] < 0){											//Check if the process was created
			perror("Error creating Fork");
			return 1;
		}

		if(pid_array[i] == 0){											//In the child process
			
			
            printf("C%d: Process %d generated random number %d\n",i, getpid(), num);	//Prints number genereted by Child i
            
			close(fd[i][1]);											//close read pipe
			
			int num2;
			read(fd[i][0], &num2, sizeof(int));							//read the number transfered
			printf ("%d vs %d\n",num,num2);
			if(num2 > num){												//compare the numbers and writes the biggest one in the pipe
				write(fd[i+1][1], &num2, sizeof(int));
			}else{
				write(fd[i+1][1], &num, sizeof(int));
			}
			
			
			close(fd[i][0]);											//close the pipe rea
			exit(0);	
		}
	}


	for(int i = 0; i < CHILDS_SIZE; i++){
		waitpid(pid_array[i], &status_array[i], 0);						//Wait all childs to end
	}
	
	int num3;
		close(fd[0][1]);												//close write pipe
		read(fd[5][0], &num3, sizeof(int));								//read the number at pipe "5" that have the biggest number
		close(fd[5][0]);												//close read pipe 
	printf("%d\n",num3);
	
	
	return 0;
    }
